import type { Reciter } from "@/types/quran";

export const RECITERS: Reciter[] = [
  {
    id: 0,
    nameArabic: "عبدالرحمن السدیس",
    nameEnglish: "Abdul Rahman Al-Sudais",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server11.mp3quran.net/sds/",
  },
  {
    id: 1,
    nameArabic: "سعود الشریم",
    nameEnglish: "Saud Al-Shuraim",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server7.mp3quran.net/shur/",
  },
  {
    id: 2,
    nameArabic: "ماهر المعیقلی",
    nameEnglish: "Maher Al-Muaiqly",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server12.mp3quran.net/maher/",
  },
  {
    id: 3,
    nameArabic: "یاسر الدوسری",
    nameEnglish: "Yasir Al-Dosari",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server7.mp3quran.net/dosari/",
  },
  {
    id: 4,
    nameArabic: "عبدالباسط عبدالصمد",
    nameEnglish: "Abdul Basit Abd us-Samad",
    country: "مصر",
    style: "مجود",
    baseUrl: "https://server7.mp3quran.net/basit/",
  },
  {
    id: 5,
    nameArabic: "محمود خلیل الحصری",
    nameEnglish: "Mahmoud Khalil Al-Husary",
    country: "مصر",
    style: "مرتل",
    baseUrl: "https://server13.mp3quran.net/husr/",
  },
  {
    id: 6,
    nameArabic: "محمد صدیق المنشاوی",
    nameEnglish: "Muhammad Siddiq Al-Minshawi",
    country: "مصر",
    style: "مجود",
    baseUrl: "https://server10.mp3quran.net/minsh/",
  },
  {
    id: 7,
    nameArabic: "احمد بن علی العجمی",
    nameEnglish: "Ahmad Ibn Ali Al-Ajmi",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server10.mp3quran.net/ajm/",
  },
  {
    id: 8,
    nameArabic: "سعد الغامدی",
    nameEnglish: "Saad Al-Ghamdi",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server7.mp3quran.net/s_gmd/",
  },
  {
    id: 9,
    nameArabic: "احمد الشاطری",
    nameEnglish: "Ahmad Al-Shatri",
    country: "سعودی عرب",
    style: "مرتل",
    baseUrl: "https://server11.mp3quran.net/shatri/",
  },
];
