import type { Surah } from "@/types/quran";

export const SURAHS: Surah[] = [
  { number: 1, nameArabic: "الْفَاتِحَة", nameEnglish: "Al-Fatihah", nameUrdu: "الفاتحہ", nameTransliteration: "Al-Fatihah", meaning: "The Opening", meaningUrdu: "کھولنے والی", verses: 7, type: "Meccan", para: 1, order: 5 },
  { number: 2, nameArabic: "الْبَقَرَة", nameEnglish: "Al-Baqarah", nameUrdu: "البقرہ", nameTransliteration: "Al-Baqarah", meaning: "The Cow", meaningUrdu: "گائے", verses: 286, type: "Medinan", para: 1, order: 87 },
  { number: 3, nameArabic: "آلِ عِمْرَان", nameEnglish: "Ali 'Imran", nameUrdu: "آل عمران", nameTransliteration: "Ali Imran", meaning: "The Family of Imran", meaningUrdu: "آل عمران", verses: 200, type: "Medinan", para: 3, order: 89 },
  { number: 4, nameArabic: "النِّسَاء", nameEnglish: "An-Nisa", nameUrdu: "النساء", nameTransliteration: "An-Nisa", meaning: "The Women", meaningUrdu: "عورتیں", verses: 176, type: "Medinan", para: 4, order: 92 },
  { number: 5, nameArabic: "الْمَائِدَة", nameEnglish: "Al-Ma'idah", nameUrdu: "المائدہ", nameTransliteration: "Al-Maidah", meaning: "The Table Spread", meaningUrdu: "دسترخوان", verses: 120, type: "Medinan", para: 6, order: 112 },
  { number: 6, nameArabic: "الْأَنْعَام", nameEnglish: "Al-An'am", nameUrdu: "الانعام", nameTransliteration: "Al-Anam", meaning: "The Cattle", meaningUrdu: "مویشی", verses: 165, type: "Meccan", para: 7, order: 55 },
  { number: 7, nameArabic: "الْأَعْرَاف", nameEnglish: "Al-A'raf", nameUrdu: "الاعراف", nameTransliteration: "Al-Araf", meaning: "The Heights", meaningUrdu: "بلندیاں", verses: 206, type: "Meccan", para: 8, order: 39 },
  { number: 8, nameArabic: "الْأَنفَال", nameEnglish: "Al-Anfal", nameUrdu: "الانفال", nameTransliteration: "Al-Anfal", meaning: "The Spoils of War", meaningUrdu: "غنیمتیں", verses: 75, type: "Medinan", para: 9, order: 88 },
  { number: 9, nameArabic: "التَّوْبَة", nameEnglish: "At-Tawbah", nameUrdu: "التوبہ", nameTransliteration: "At-Tawbah", meaning: "The Repentance", meaningUrdu: "توبہ", verses: 129, type: "Medinan", para: 10, order: 113 },
  { number: 10, nameArabic: "يُونُس", nameEnglish: "Yunus", nameUrdu: "یونس", nameTransliteration: "Yunus", meaning: "Jonah", meaningUrdu: "یونس علیہ السلام", verses: 109, type: "Meccan", para: 11, order: 51 },
  { number: 11, nameArabic: "هُود", nameEnglish: "Hud", nameUrdu: "ہود", nameTransliteration: "Hud", meaning: "Hud", meaningUrdu: "ہود علیہ السلام", verses: 123, type: "Meccan", para: 11, order: 52 },
  { number: 12, nameArabic: "يُوسُف", nameEnglish: "Yusuf", nameUrdu: "یوسف", nameTransliteration: "Yusuf", meaning: "Joseph", meaningUrdu: "یوسف علیہ السلام", verses: 111, type: "Meccan", para: 12, order: 53 },
  { number: 13, nameArabic: "الرَّعْد", nameEnglish: "Ar-Ra'd", nameUrdu: "الرعد", nameTransliteration: "Ar-Rad", meaning: "The Thunder", meaningUrdu: "گرج", verses: 43, type: "Medinan", para: 13, order: 96 },
  { number: 14, nameArabic: "إِبْرَاهِيم", nameEnglish: "Ibrahim", nameUrdu: "ابراہیم", nameTransliteration: "Ibrahim", meaning: "Abraham", meaningUrdu: "ابراہیم علیہ السلام", verses: 52, type: "Meccan", para: 13, order: 72 },
  { number: 15, nameArabic: "الْحِجْر", nameEnglish: "Al-Hijr", nameUrdu: "الحجر", nameTransliteration: "Al-Hijr", meaning: "The Rocky Tract", meaningUrdu: "پتھریلی زمین", verses: 99, type: "Meccan", para: 14, order: 54 },
  { number: 16, nameArabic: "النَّحْل", nameEnglish: "An-Nahl", nameUrdu: "النحل", nameTransliteration: "An-Nahl", meaning: "The Bee", meaningUrdu: "مکھی", verses: 128, type: "Meccan", para: 14, order: 70 },
  { number: 17, nameArabic: "الْإِسْرَاء", nameEnglish: "Al-Isra", nameUrdu: "الاسراء", nameTransliteration: "Al-Isra", meaning: "The Night Journey", meaningUrdu: "رات کا سفر", verses: 111, type: "Meccan", para: 15, order: 50 },
  { number: 18, nameArabic: "الْكَهْف", nameEnglish: "Al-Kahf", nameUrdu: "الکہف", nameTransliteration: "Al-Kahf", meaning: "The Cave", meaningUrdu: "غار", verses: 110, type: "Meccan", para: 15, order: 69 },
  { number: 19, nameArabic: "مَرْيَم", nameEnglish: "Maryam", nameUrdu: "مریم", nameTransliteration: "Maryam", meaning: "Mary", meaningUrdu: "مریم علیہا السلام", verses: 98, type: "Meccan", para: 16, order: 44 },
  { number: 20, nameArabic: "طه", nameEnglish: "Ta-Ha", nameUrdu: "طہ", nameTransliteration: "Ta-Ha", meaning: "Ta-Ha", meaningUrdu: "طہ", verses: 135, type: "Meccan", para: 16, order: 45 },
  { number: 21, nameArabic: "الْأَنبِيَاء", nameEnglish: "Al-Anbiya", nameUrdu: "الانبیاء", nameTransliteration: "Al-Anbiya", meaning: "The Prophets", meaningUrdu: "انبیاء", verses: 112, type: "Meccan", para: 17, order: 73 },
  { number: 22, nameArabic: "الْحَج", nameEnglish: "Al-Hajj", nameUrdu: "الحج", nameTransliteration: "Al-Hajj", meaning: "The Pilgrimage", meaningUrdu: "حج", verses: 78, type: "Medinan", para: 17, order: 103 },
  { number: 23, nameArabic: "الْمُؤْمِنُون", nameEnglish: "Al-Mu'minun", nameUrdu: "المؤمنون", nameTransliteration: "Al-Muminun", meaning: "The Believers", meaningUrdu: "مومنین", verses: 118, type: "Meccan", para: 18, order: 74 },
  { number: 24, nameArabic: "النُّور", nameEnglish: "An-Nur", nameUrdu: "النور", nameTransliteration: "An-Nur", meaning: "The Light", meaningUrdu: "نور", verses: 64, type: "Medinan", para: 18, order: 102 },
  { number: 25, nameArabic: "الْفُرْقَان", nameEnglish: "Al-Furqan", nameUrdu: "الفرقان", nameTransliteration: "Al-Furqan", meaning: "The Criterion", meaningUrdu: "فرقان", verses: 77, type: "Meccan", para: 18, order: 42 },
  { number: 26, nameArabic: "الشُّعَرَاء", nameEnglish: "Ash-Shu'ara", nameUrdu: "الشعراء", nameTransliteration: "Ash-Shuara", meaning: "The Poets", meaningUrdu: "شعراء", verses: 227, type: "Meccan", para: 19, order: 47 },
  { number: 27, nameArabic: "النَّمْل", nameEnglish: "An-Naml", nameUrdu: "النمل", nameTransliteration: "An-Naml", meaning: "The Ant", meaningUrdu: "چیونٹی", verses: 93, type: "Meccan", para: 19, order: 48 },
  { number: 28, nameArabic: "الْقَصَص", nameEnglish: "Al-Qasas", nameUrdu: "القصص", nameTransliteration: "Al-Qasas", meaning: "The Stories", meaningUrdu: "قصے", verses: 88, type: "Meccan", para: 20, order: 49 },
  { number: 29, nameArabic: "الْعَنكَبُوت", nameEnglish: "Al-Ankabut", nameUrdu: "العنکبوت", nameTransliteration: "Al-Ankabut", meaning: "The Spider", meaningUrdu: "مکڑی", verses: 69, type: "Meccan", para: 20, order: 85 },
  { number: 30, nameArabic: "الرُّوم", nameEnglish: "Ar-Rum", nameUrdu: "الروم", nameTransliteration: "Ar-Rum", meaning: "The Romans", meaningUrdu: "رومی", verses: 60, type: "Meccan", para: 21, order: 84 },
  { number: 31, nameArabic: "لُقْمَان", nameEnglish: "Luqman", nameUrdu: "لقمان", nameTransliteration: "Luqman", meaning: "Luqman", meaningUrdu: "لقمان", verses: 34, type: "Meccan", para: 21, order: 57 },
  { number: 32, nameArabic: "السَّجْدَة", nameEnglish: "As-Sajdah", nameUrdu: "السجدہ", nameTransliteration: "As-Sajdah", meaning: "The Prostration", meaningUrdu: "سجدہ", verses: 30, type: "Meccan", para: 21, order: 75 },
  { number: 33, nameArabic: "الْأَحْزَاب", nameEnglish: "Al-Ahzab", nameUrdu: "الاحزاب", nameTransliteration: "Al-Ahzab", meaning: "The Combined Forces", meaningUrdu: "لشکر", verses: 73, type: "Medinan", para: 21, order: 90 },
  { number: 34, nameArabic: "سَبَأ", nameEnglish: "Saba", nameUrdu: "سبأ", nameTransliteration: "Saba", meaning: "Sheba", meaningUrdu: "سبا", verses: 54, type: "Meccan", para: 22, order: 58 },
  { number: 35, nameArabic: "فَاطِر", nameEnglish: "Fatir", nameUrdu: "فاطر", nameTransliteration: "Fatir", meaning: "Originator", meaningUrdu: "پیدا کرنے والا", verses: 45, type: "Meccan", para: 22, order: 43 },
  { number: 36, nameArabic: "يس", nameEnglish: "Ya-Sin", nameUrdu: "یس", nameTransliteration: "Ya-Sin", meaning: "Ya Sin", meaningUrdu: "یس", verses: 83, type: "Meccan", para: 22, order: 41 },
  { number: 37, nameArabic: "الصَّافَّات", nameEnglish: "As-Saffat", nameUrdu: "الصافات", nameTransliteration: "As-Saffat", meaning: "Those Ranged in Ranks", meaningUrdu: "صف بستہ فرشتے", verses: 182, type: "Meccan", para: 23, order: 56 },
  { number: 38, nameArabic: "ص", nameEnglish: "Sad", nameUrdu: "صٓ", nameTransliteration: "Sad", meaning: "The Letter Sad", meaningUrdu: "صاد", verses: 88, type: "Meccan", para: 23, order: 38 },
  { number: 39, nameArabic: "الزُّمَر", nameEnglish: "Az-Zumar", nameUrdu: "الزمر", nameTransliteration: "Az-Zumar", meaning: "The Troops", meaningUrdu: "گروہ", verses: 75, type: "Meccan", para: 23, order: 59 },
  { number: 40, nameArabic: "غَافِر", nameEnglish: "Ghafir", nameUrdu: "غافر", nameTransliteration: "Ghafir", meaning: "The Forgiver", meaningUrdu: "بخشنے والا", verses: 85, type: "Meccan", para: 24, order: 60 },
  { number: 41, nameArabic: "فُصِّلَت", nameEnglish: "Fussilat", nameUrdu: "فصلت", nameTransliteration: "Fussilat", meaning: "Explained in Detail", meaningUrdu: "تفصیل", verses: 54, type: "Meccan", para: 24, order: 61 },
  { number: 42, nameArabic: "الشُّورَى", nameEnglish: "Ash-Shuraa", nameUrdu: "الشوری", nameTransliteration: "Ash-Shura", meaning: "The Consultation", meaningUrdu: "مشاورت", verses: 53, type: "Meccan", para: 25, order: 62 },
  { number: 43, nameArabic: "الزُّخْرُف", nameEnglish: "Az-Zukhruf", nameUrdu: "الزخرف", nameTransliteration: "Az-Zukhruf", meaning: "The Ornaments of Gold", meaningUrdu: "سونے کی زیب و زینت", verses: 89, type: "Meccan", para: 25, order: 63 },
  { number: 44, nameArabic: "الدُّخَان", nameEnglish: "Ad-Dukhan", nameUrdu: "الدخان", nameTransliteration: "Ad-Dukhan", meaning: "The Smoke", meaningUrdu: "دھواں", verses: 59, type: "Meccan", para: 25, order: 64 },
  { number: 45, nameArabic: "الْجَاثِيَة", nameEnglish: "Al-Jathiyah", nameUrdu: "الجاثیہ", nameTransliteration: "Al-Jathiyah", meaning: "The Crouching", meaningUrdu: "گھٹنے ٹیکنا", verses: 37, type: "Meccan", para: 25, order: 65 },
  { number: 46, nameArabic: "الْأَحْقَاف", nameEnglish: "Al-Ahqaf", nameUrdu: "الاحقاف", nameTransliteration: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills", meaningUrdu: "ریت کے ٹیلے", verses: 35, type: "Meccan", para: 26, order: 66 },
  { number: 47, nameArabic: "مُحَمَّد", nameEnglish: "Muhammad", nameUrdu: "محمد", nameTransliteration: "Muhammad", meaning: "Muhammad", meaningUrdu: "محمد ﷺ", verses: 38, type: "Medinan", para: 26, order: 95 },
  { number: 48, nameArabic: "الْفَتْح", nameEnglish: "Al-Fath", nameUrdu: "الفتح", nameTransliteration: "Al-Fath", meaning: "The Victory", meaningUrdu: "فتح", verses: 29, type: "Medinan", para: 26, order: 111 },
  { number: 49, nameArabic: "الْحُجُرَات", nameEnglish: "Al-Hujurat", nameUrdu: "الحجرات", nameTransliteration: "Al-Hujurat", meaning: "The Rooms", meaningUrdu: "کمرے", verses: 18, type: "Medinan", para: 26, order: 106 },
  { number: 50, nameArabic: "ق", nameEnglish: "Qaf", nameUrdu: "قٓ", nameTransliteration: "Qaf", meaning: "The Letter Qaf", meaningUrdu: "قاف", verses: 45, type: "Meccan", para: 26, order: 34 },
  { number: 51, nameArabic: "الذَّارِيَات", nameEnglish: "Adh-Dhariyat", nameUrdu: "الذاریات", nameTransliteration: "Adh-Dhariyat", meaning: "The Winnowing Winds", meaningUrdu: "اڑانے والی ہوائیں", verses: 60, type: "Meccan", para: 26, order: 67 },
  { number: 52, nameArabic: "الطُّور", nameEnglish: "At-Tur", nameUrdu: "الطور", nameTransliteration: "At-Tur", meaning: "The Mount", meaningUrdu: "کوہ طور", verses: 49, type: "Meccan", para: 27, order: 76 },
  { number: 53, nameArabic: "النَّجْم", nameEnglish: "An-Najm", nameUrdu: "النجم", nameTransliteration: "An-Najm", meaning: "The Star", meaningUrdu: "ستارہ", verses: 62, type: "Meccan", para: 27, order: 23 },
  { number: 54, nameArabic: "الْقَمَر", nameEnglish: "Al-Qamar", nameUrdu: "القمر", nameTransliteration: "Al-Qamar", meaning: "The Moon", meaningUrdu: "چاند", verses: 55, type: "Meccan", para: 27, order: 37 },
  { number: 55, nameArabic: "الرَّحْمَن", nameEnglish: "Ar-Rahman", nameUrdu: "الرحمن", nameTransliteration: "Ar-Rahman", meaning: "The Beneficent", meaningUrdu: "بڑا مہربان", verses: 78, type: "Medinan", para: 27, order: 97 },
  { number: 56, nameArabic: "الْوَاقِعَة", nameEnglish: "Al-Waqi'ah", nameUrdu: "الواقعہ", nameTransliteration: "Al-Waqiah", meaning: "The Inevitable", meaningUrdu: "ضرور ہونے والی", verses: 96, type: "Meccan", para: 27, order: 46 },
  { number: 57, nameArabic: "الْحَدِيد", nameEnglish: "Al-Hadid", nameUrdu: "الحدید", nameTransliteration: "Al-Hadid", meaning: "The Iron", meaningUrdu: "لوہا", verses: 29, type: "Medinan", para: 27, order: 94 },
  { number: 58, nameArabic: "الْمُجَادِلَة", nameEnglish: "Al-Mujadila", nameUrdu: "المجادلہ", nameTransliteration: "Al-Mujadila", meaning: "The Pleading Woman", meaningUrdu: "بحث کرنے والی", verses: 22, type: "Medinan", para: 28, order: 105 },
  { number: 59, nameArabic: "الْحَشْر", nameEnglish: "Al-Hashr", nameUrdu: "الحشر", nameTransliteration: "Al-Hashr", meaning: "The Exile", meaningUrdu: "جلاوطنی", verses: 24, type: "Medinan", para: 28, order: 101 },
  { number: 60, nameArabic: "الْمُمْتَحِنَة", nameEnglish: "Al-Mumtahanah", nameUrdu: "الممتحنہ", nameTransliteration: "Al-Mumtahanah", meaning: "She that is to be Examined", meaningUrdu: "آزمائی جانے والی", verses: 13, type: "Medinan", para: 28, order: 91 },
  { number: 61, nameArabic: "الصَّف", nameEnglish: "As-Saf", nameUrdu: "الصف", nameTransliteration: "As-Saf", meaning: "The Ranks", meaningUrdu: "صف", verses: 14, type: "Medinan", para: 28, order: 109 },
  { number: 62, nameArabic: "الْجُمُعَة", nameEnglish: "Al-Jumu'ah", nameUrdu: "الجمعہ", nameTransliteration: "Al-Jumuah", meaning: "Friday", meaningUrdu: "جمعہ", verses: 11, type: "Medinan", para: 28, order: 110 },
  { number: 63, nameArabic: "الْمُنَافِقُون", nameEnglish: "Al-Munafiqun", nameUrdu: "المنافقون", nameTransliteration: "Al-Munafiqun", meaning: "The Hypocrites", meaningUrdu: "منافقین", verses: 11, type: "Medinan", para: 28, order: 104 },
  { number: 64, nameArabic: "التَّغَابُن", nameEnglish: "At-Taghabun", nameUrdu: "التغابن", nameTransliteration: "At-Taghabun", meaning: "The Mutual Disillusion", meaningUrdu: "نقصان", verses: 18, type: "Medinan", para: 28, order: 108 },
  { number: 65, nameArabic: "الطَّلَاق", nameEnglish: "At-Talaq", nameUrdu: "الطلاق", nameTransliteration: "At-Talaq", meaning: "The Divorce", meaningUrdu: "طلاق", verses: 12, type: "Medinan", para: 28, order: 99 },
  { number: 66, nameArabic: "التَّحْرِيم", nameEnglish: "At-Tahrim", nameUrdu: "التحریم", nameTransliteration: "At-Tahrim", meaning: "The Prohibition", meaningUrdu: "حرام کرنا", verses: 12, type: "Medinan", para: 28, order: 107 },
  { number: 67, nameArabic: "الْمُلْك", nameEnglish: "Al-Mulk", nameUrdu: "الملک", nameTransliteration: "Al-Mulk", meaning: "The Sovereignty", meaningUrdu: "بادشاہت", verses: 30, type: "Meccan", para: 29, order: 77 },
  { number: 68, nameArabic: "الْقَلَم", nameEnglish: "Al-Qalam", nameUrdu: "القلم", nameTransliteration: "Al-Qalam", meaning: "The Pen", meaningUrdu: "قلم", verses: 52, type: "Meccan", para: 29, order: 2 },
  { number: 69, nameArabic: "الْحَاقَّة", nameEnglish: "Al-Haqqah", nameUrdu: "الحاقہ", nameTransliteration: "Al-Haqqah", meaning: "The Reality", meaningUrdu: "حق بات", verses: 52, type: "Meccan", para: 29, order: 78 },
  { number: 70, nameArabic: "الْمَعَارِج", nameEnglish: "Al-Ma'arij", nameUrdu: "المعارج", nameTransliteration: "Al-Maarij", meaning: "The Ascending Stairways", meaningUrdu: "بلند درجات", verses: 44, type: "Meccan", para: 29, order: 79 },
  { number: 71, nameArabic: "نُوح", nameEnglish: "Nuh", nameUrdu: "نوح", nameTransliteration: "Nuh", meaning: "Noah", meaningUrdu: "نوح علیہ السلام", verses: 28, type: "Meccan", para: 29, order: 71 },
  { number: 72, nameArabic: "الْجِن", nameEnglish: "Al-Jinn", nameUrdu: "الجن", nameTransliteration: "Al-Jinn", meaning: "The Jinn", meaningUrdu: "جنات", verses: 28, type: "Meccan", para: 29, order: 40 },
  { number: 73, nameArabic: "الْمُزَّمِّل", nameEnglish: "Al-Muzzammil", nameUrdu: "المزمل", nameTransliteration: "Al-Muzzammil", meaning: "The Enshrouded One", meaningUrdu: "کپڑا اوڑھنے والا", verses: 20, type: "Meccan", para: 29, order: 3 },
  { number: 74, nameArabic: "الْمُدَّثِّر", nameEnglish: "Al-Muddaththir", nameUrdu: "المدثر", nameTransliteration: "Al-Muddaththir", meaning: "The Cloaked One", meaningUrdu: "چادر اوڑھنے والا", verses: 56, type: "Meccan", para: 29, order: 4 },
  { number: 75, nameArabic: "الْقِيَامَة", nameEnglish: "Al-Qiyamah", nameUrdu: "القیامہ", nameTransliteration: "Al-Qiyamah", meaning: "The Resurrection", meaningUrdu: "قیامت", verses: 40, type: "Meccan", para: 29, order: 31 },
  { number: 76, nameArabic: "الْإِنسَان", nameEnglish: "Al-Insan", nameUrdu: "الانسان", nameTransliteration: "Al-Insan", meaning: "The Man", meaningUrdu: "انسان", verses: 31, type: "Medinan", para: 29, order: 98 },
  { number: 77, nameArabic: "الْمُرْسَلَات", nameEnglish: "Al-Mursalat", nameUrdu: "المرسلات", nameTransliteration: "Al-Mursalat", meaning: "The Emissaries", meaningUrdu: "قاصد", verses: 50, type: "Meccan", para: 29, order: 33 },
  { number: 78, nameArabic: "النَّبَأ", nameEnglish: "An-Naba", nameUrdu: "النبأ", nameTransliteration: "An-Naba", meaning: "The Tidings", meaningUrdu: "خبر", verses: 40, type: "Meccan", para: 30, order: 80 },
  { number: 79, nameArabic: "النَّازِعَات", nameEnglish: "An-Naziat", nameUrdu: "النازعات", nameTransliteration: "An-Naziat", meaning: "Those Who Drag Forth", meaningUrdu: "کھینچنے والے", verses: 46, type: "Meccan", para: 30, order: 81 },
  { number: 80, nameArabic: "عَبَسَ", nameEnglish: "Abasa", nameUrdu: "عبس", nameTransliteration: "Abasa", meaning: "He Frowned", meaningUrdu: "منہ بنایا", verses: 42, type: "Meccan", para: 30, order: 24 },
  { number: 81, nameArabic: "التَّكْوِير", nameEnglish: "At-Takwir", nameUrdu: "التکویر", nameTransliteration: "At-Takwir", meaning: "The Overthrowing", meaningUrdu: "لپیٹنا", verses: 29, type: "Meccan", para: 30, order: 7 },
  { number: 82, nameArabic: "الْإِنفِطَار", nameEnglish: "Al-Infitar", nameUrdu: "الانفطار", nameTransliteration: "Al-Infitar", meaning: "The Cleaving", meaningUrdu: "پھٹنا", verses: 19, type: "Meccan", para: 30, order: 82 },
  { number: 83, nameArabic: "الْمُطَفِّفِين", nameEnglish: "Al-Mutaffifin", nameUrdu: "المطففین", nameTransliteration: "Al-Mutaffifin", meaning: "The Defrauding", meaningUrdu: "ناپ تول میں کمی", verses: 36, type: "Meccan", para: 30, order: 86 },
  { number: 84, nameArabic: "الْإِنشِقَاق", nameEnglish: "Al-Inshiqaq", nameUrdu: "الانشقاق", nameTransliteration: "Al-Inshiqaq", meaning: "The Sundering", meaningUrdu: "پھٹ جانا", verses: 25, type: "Meccan", para: 30, order: 83 },
  { number: 85, nameArabic: "الْبُرُوج", nameEnglish: "Al-Buruj", nameUrdu: "البروج", nameTransliteration: "Al-Buruj", meaning: "The Mansions of the Stars", meaningUrdu: "آسمانی برج", verses: 22, type: "Meccan", para: 30, order: 27 },
  { number: 86, nameArabic: "الطَّارِق", nameEnglish: "At-Tariq", nameUrdu: "الطارق", nameTransliteration: "At-Tariq", meaning: "The Morning Star", meaningUrdu: "رات کو آنے والا", verses: 17, type: "Meccan", para: 30, order: 36 },
  { number: 87, nameArabic: "الْأَعْلَى", nameEnglish: "Al-Ala", nameUrdu: "الاعلی", nameTransliteration: "Al-Ala", meaning: "The Most High", meaningUrdu: "سب سے بلند", verses: 19, type: "Meccan", para: 30, order: 8 },
  { number: 88, nameArabic: "الْغَاشِيَة", nameEnglish: "Al-Ghashiyah", nameUrdu: "الغاشیہ", nameTransliteration: "Al-Ghashiyah", meaning: "The Overwhelming", meaningUrdu: "ڈھانپ لینے والی", verses: 26, type: "Meccan", para: 30, order: 68 },
  { number: 89, nameArabic: "الْفَجْر", nameEnglish: "Al-Fajr", nameUrdu: "الفجر", nameTransliteration: "Al-Fajr", meaning: "The Dawn", meaningUrdu: "فجر", verses: 30, type: "Meccan", para: 30, order: 10 },
  { number: 90, nameArabic: "الْبَلَد", nameEnglish: "Al-Balad", nameUrdu: "البلد", nameTransliteration: "Al-Balad", meaning: "The City", meaningUrdu: "شہر", verses: 20, type: "Meccan", para: 30, order: 35 },
  { number: 91, nameArabic: "الشَّمْس", nameEnglish: "Ash-Shams", nameUrdu: "الشمس", nameTransliteration: "Ash-Shams", meaning: "The Sun", meaningUrdu: "سورج", verses: 15, type: "Meccan", para: 30, order: 26 },
  { number: 92, nameArabic: "اللَّيْل", nameEnglish: "Al-Layl", nameUrdu: "اللیل", nameTransliteration: "Al-Layl", meaning: "The Night", meaningUrdu: "رات", verses: 21, type: "Meccan", para: 30, order: 9 },
  { number: 93, nameArabic: "الضُّحَى", nameEnglish: "Ad-Duha", nameUrdu: "الضحی", nameTransliteration: "Ad-Duha", meaning: "The Morning Hours", meaningUrdu: "چاشت", verses: 11, type: "Meccan", para: 30, order: 11 },
  { number: 94, nameArabic: "الشَّرْح", nameEnglish: "Ash-Sharh", nameUrdu: "الشرح", nameTransliteration: "Ash-Sharh", meaning: "The Opening Up", meaningUrdu: "کھولنا", verses: 8, type: "Meccan", para: 30, order: 12 },
  { number: 95, nameArabic: "التِّين", nameEnglish: "At-Tin", nameUrdu: "التین", nameTransliteration: "At-Tin", meaning: "The Fig", meaningUrdu: "انجیر", verses: 8, type: "Meccan", para: 30, order: 28 },
  { number: 96, nameArabic: "الْعَلَق", nameEnglish: "Al-Alaq", nameUrdu: "العلق", nameTransliteration: "Al-Alaq", meaning: "The Clot", meaningUrdu: "جمے خون", verses: 19, type: "Meccan", para: 30, order: 1 },
  { number: 97, nameArabic: "الْقَدْر", nameEnglish: "Al-Qadr", nameUrdu: "القدر", nameTransliteration: "Al-Qadr", meaning: "The Power", meaningUrdu: "قدر", verses: 5, type: "Meccan", para: 30, order: 25 },
  { number: 98, nameArabic: "الْبَيِّنَة", nameEnglish: "Al-Bayyinah", nameUrdu: "البینہ", nameTransliteration: "Al-Bayyinah", meaning: "The Clear Proof", meaningUrdu: "واضح دلیل", verses: 8, type: "Medinan", para: 30, order: 100 },
  { number: 99, nameArabic: "الزَّلْزَلَة", nameEnglish: "Az-Zalzalah", nameUrdu: "الزلزلہ", nameTransliteration: "Az-Zalzalah", meaning: "The Earthquake", meaningUrdu: "زلزلہ", verses: 8, type: "Medinan", para: 30, order: 93 },
  { number: 100, nameArabic: "الْعَادِيَات", nameEnglish: "Al-Adiyat", nameUrdu: "العادیات", nameTransliteration: "Al-Adiyat", meaning: "The Coursers", meaningUrdy: "دوڑنے والے گھوڑے", meaningUrdu: "دوڑنے والے", verses: 11, type: "Meccan", para: 30, order: 14 },
  { number: 101, nameArabic: "الْقَارِعَة", nameEnglish: "Al-Qariah", nameUrdu: "القارعہ", nameTransliteration: "Al-Qariah", meaning: "The Calamity", meaningUrdu: "کھڑکھڑانے والی", verses: 11, type: "Meccan", para: 30, order: 30 },
  { number: 102, nameArabic: "التَّكَاثُر", nameEnglish: "At-Takathur", nameUrdu: "التکاثر", nameTransliteration: "At-Takathur", meaning: "The Rivalry in World Increase", meaningUrdu: "مال کی فراوانی میں مقابلہ", verses: 8, type: "Meccan", para: 30, order: 16 },
  { number: 103, nameArabic: "الْعَصْر", nameEnglish: "Al-Asr", nameUrdu: "العصر", nameTransliteration: "Al-Asr", meaning: "The Declining Day", meaningUrdu: "زمانہ", verses: 3, type: "Meccan", para: 30, order: 13 },
  { number: 104, nameArabic: "الْهُمَزَة", nameEnglish: "Al-Humazah", nameUrdu: "الہمزہ", nameTransliteration: "Al-Humazah", meaning: "The Traducer", meaningUrdu: "بدگو", verses: 9, type: "Meccan", para: 30, order: 32 },
  { number: 105, nameArabic: "الْفِيل", nameEnglish: "Al-Fil", nameUrdu: "الفیل", nameTransliteration: "Al-Fil", meaning: "The Elephant", meaningUrdu: "ہاتھی", verses: 5, type: "Meccan", para: 30, order: 19 },
  { number: 106, nameArabic: "قُرَيْش", nameEnglish: "Quraysh", nameUrdu: "قریش", nameTransliteration: "Quraysh", meaning: "Quraysh", meaningUrdu: "قریش قبیلہ", verses: 4, type: "Meccan", para: 30, order: 29 },
  { number: 107, nameArabic: "الْمَاعُون", nameEnglish: "Al-Maun", nameUrdu: "الماعون", nameTransliteration: "Al-Maun", meaning: "The Small Kindnesses", meaningUrdu: "معمولی مدد", verses: 7, type: "Meccan", para: 30, order: 17 },
  { number: 108, nameArabic: "الْكَوْثَر", nameEnglish: "Al-Kawthar", nameUrdu: "الکوثر", nameTransliteration: "Al-Kawthar", meaning: "The Abundance", meaningUrdu: "کوثر", verses: 3, type: "Meccan", para: 30, order: 15 },
  { number: 109, nameArabic: "الْكَافِرُون", nameEnglish: "Al-Kafirun", nameUrdu: "الکافرون", nameTransliteration: "Al-Kafirun", meaning: "The Disbelievers", meaningUrdu: "کافر", verses: 6, type: "Meccan", para: 30, order: 18 },
  { number: 110, nameArabic: "النَّصْر", nameEnglish: "An-Nasr", nameUrdu: "النصر", nameTransliteration: "An-Nasr", meaning: "The Divine Support", meaningUrdu: "مدد", verses: 3, type: "Medinan", para: 30, order: 114 },
  { number: 111, nameArabic: "الْمَسَد", nameEnglish: "Al-Masad", nameUrdu: "المسد", nameTransliteration: "Al-Masad", meaning: "The Palm Fiber", meaningUrdu: "کھجور کی رسی", verses: 5, type: "Meccan", para: 30, order: 6 },
  { number: 112, nameArabic: "الْإِخْلَاص", nameEnglish: "Al-Ikhlas", nameUrdu: "الاخلاص", nameTransliteration: "Al-Ikhlas", meaning: "The Sincerity", meaningUrdu: "اخلاص", verses: 4, type: "Meccan", para: 30, order: 22 },
  { number: 113, nameArabic: "الْفَلَق", nameEnglish: "Al-Falaq", nameUrdu: "الفلق", nameTransliteration: "Al-Falaq", meaning: "The Daybreak", meaningUrdu: "پھٹنے والا", verses: 5, type: "Meccan", para: 30, order: 20 },
  { number: 114, nameArabic: "النَّاس", nameEnglish: "An-Nas", nameUrdu: "الناس", nameTransliteration: "An-Nas", meaning: "Mankind", meaningUrdu: "لوگ", verses: 6, type: "Meccan", para: 30, order: 21 },
];

export const SURAH_COLORS = [
  "from-green-400 to-emerald-500",
  "from-blue-400 to-blue-600",
  "from-purple-400 to-purple-600",
  "from-rose-400 to-rose-600",
  "from-amber-400 to-amber-600",
  "from-teal-400 to-teal-600",
  "from-indigo-400 to-indigo-600",
  "from-orange-400 to-orange-600",
  "from-cyan-400 to-cyan-600",
  "from-pink-400 to-pink-600",
];
